--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.4 Revision 4 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : R2D2
-- User name     : Arturo
-- Time stamp    : Fri Apr 25 10:47:32 2025
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.StateMach
-- Last modified : Thu Apr 10 19:40:54 2025
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;

entity StateMach is
  port (
    AddRoundKeyu3En    : out    std_logic;
    AddRoundKeyu3Fin   : in     std_logic;
    AddRoundu0En       : out    std_logic;
    AddRoundu0Fin      : in     std_logic;
    AddRoundu7En       : out    std_logic;
    AddRoundu7Fin      : in     std_logic;
    Clk                : in     std_logic;
    InvMixColumnsu4En  : out    std_logic;
    InvMixColumnsu4Fin : in     std_logic;
    InvShiftRowsu1En   : out    std_logic;
    InvShiftRowsu1Fin  : in     std_logic;
    InvShiftRowsu5En   : out    std_logic;
    InvShiftRowsu5Fin  : in     std_logic;
    InvSubBytesu2En    : out    std_logic;
    InvSubBytesu2Fin   : in     std_logic;
    InvSubBytesu6En    : out    std_logic;
    InvSubBytesu6Fin   : in     std_logic;
    KeyEn              : out    std_logic;
    KeyFin             : in     std_logic;
    KeySel             : out    std_logic_vector(3 downto 0);
    MuxSel             : out    std_logic;
    Rst                : in     std_logic);
end entity StateMach;

--------------------------------------------------------------------------------
-- Object        : Architecture design.StateMach.rtl
-- Last modified : Thu Apr 10 19:40:54 2025
--------------------------------------------------------------------------------


architecture rtl of StateMach is

begin

end architecture rtl ; -- of StateMach

