--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.4 Revision 4 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : R2D2
-- User name     : Arturo
-- Time stamp    : Fri Apr 25 10:47:32 2025
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.InvMixColumns
-- Last modified : Fri Apr 11 01:32:01 2025
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;

entity InvMixColumns is
  port (
    Clk    : in     std_logic;
    Enable : in     std_logic;
    Finish : out    std_logic;
    Rst    : in     std_logic;
    TxtIn  : in     std_logic_vector(127 downto 0);
    TxtOut : out    std_logic_vector(127 downto 0));
end entity InvMixColumns;

--------------------------------------------------------------------------------
-- Object        : Architecture design.InvMixColumns.rtl
-- Last modified : Fri Apr 11 01:32:01 2025
--------------------------------------------------------------------------------


architecture rtl of InvMixColumns is

begin

end architecture rtl ; -- of InvMixColumns

