--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.2 Revision 6 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : calypso1
-- User name     : RickWare
-- Time stamp    : Tue May 12 16:56:12 2009
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.Top  Testbench
-- Last modified : Tue May 12 16:46:56 2009.
--------------------------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;

ENTITY Top_tb IS
END Top_tb;

ARCHITECTURE behavior OF Top_tb IS

  -- Component Declaration for the Unit Under Test (UUT)
  COMPONENT Top
  PORT(
    Clk        		: in     std_logic;
    CypherText 		: out    std_logic_vector(127 downto 0);
	 CipherKeyInput	: in     std_logic_vector(127 downto 0);
    PlainText  		: in     std_logic_vector(127 downto 0);
    Reset      		: in     std_logic;
	 
	 --Lineas de maquina de estado, para prueba.
	 oAddRoundu0En    : out    std_logic;
    oAddRoundu4En    : out    std_logic;
    oAddRoundu7En    : out    std_logic;
    oKeyEn           : out    std_logic;
    oKeySel          : out    std_logic_vector(3 downto 0);
    oMixColumnsu3En  : out    std_logic;
    oMuxSel          : out    std_logic;
    oShiftRowsu2En   : out    std_logic;
    oShiftRowsu6En   : out    std_logic;
    oSubBytesu1En    : out    std_logic;
    oSubBytesu5En    : out    std_logic;
	 oEderFinish   	: out    std_logic;
	 oSubytesFinish   : out    std_logic;
	 oMarkitosFinish  : out    std_logic
    );
  END COMPONENT;
  
  -- Inputs
  signal Clk            : std_logic := '0';
  signal Reset          : std_logic := '1';
  signal CipherKeyInput	: std_logic_vector(127 downto 0) := (others => '0');
  signal PlainText	   : std_logic_vector(127 downto 0) := (others => '0');
  
  -- Outputs
  signal CypherText	   : std_logic_vector(127 downto 0);
  signal oAddRoundu0En  : std_logic;
  signal oAddRoundu4En  : std_logic;
  signal oAddRoundu7En  : std_logic;
  signal oKeyEn         : std_logic;
  signal oKeySel        : std_logic_vector(3 downto 0);
  signal oMixColumnsu3En: std_logic;
  signal oMuxSel        : std_logic;
  signal oShiftRowsu2En : std_logic;
  signal oShiftRowsu6En : std_logic;
  signal oSubBytesu1En  : std_logic;
  signal oSubBytesu5En  : std_logic;
  signal	oEderFinish   	: std_logic;
  signal	oSubytesFinish : std_logic;
  signal	oMarkitosFinish: std_logic;
  
  -- Clock
  constant Clk_period : time := 10 ns;

begin
  -- Instantiate the Unit Under Test (UUT)
  uut: Top port map (
    Clk					=> Clk,
    CypherText			=> CypherText,
	 CipherKeyInput	=>CipherKeyInput,
    PlainText			=> PlainText,
    Reset				=> Reset,
	 oAddRoundu0En		=> oAddRoundu0En,
    oAddRoundu4En		=> oAddRoundu4En,
    oAddRoundu7En		=> oAddRoundu7En,
    oKeyEn				=> oKeyEn,
    oKeySel				=> oKeySel,
    oMixColumnsu3En	=> oMixColumnsu3En,
    oMuxSel				=> oMuxSel,
    oShiftRowsu2En	=> oShiftRowsu2En,
    oShiftRowsu6En	=> oShiftRowsu6En,
    oSubBytesu1En		=> oSubBytesu1En,
    oSubBytesu5En		=> oSubBytesu5En,
	 oEderFinish		=> oEderFinish,
	 oSubytesFinish	=> oSubytesFinish,
	 oMarkitosFinish	=> oMarkitosFinish
	 );
	 
  -- Clock process definitions
  Clk_process: process
  begin
    Clk <= '0';
    wait for Clk_period/2;
    Clk <= '1';
    wait for Clk_period/2;
  end process;
  
  --Stimulus process
  stim_proc: process
  begin
    -- hold reset state for 100 ns.
    wait for Clk_period*10;
	 
	 -- Stimulus
	 Reset <= '0';
	 -- By Columns
	 PlainText			<= x"3243F6A8885A308D313198A2E0370734";
	 CipherKeyInput	<= x"2B7E151628AED2A6ABF7158809CF4F3C";
	 
	 -- By Rows
	 -- PlainText      <= x"328831E0435A3137F6309807A88DA234";
	 -- CipherKeyInput <= x"2B28AB097EAEF7CF15D2154F16A6883C";
	 
	 
	 wait;
	 
  end process;

	 
end;



