--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.4 Revision 4 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : v2-Lap
-- User name     : ricks
-- Time stamp    : Mon Apr 07 09:53:12 2025
--
-- Designed by   : Artwwr
-- Company       : 
-- Project info  : Round Key para encriptacion y decriptacion o sea es lo mismo
--				   Pa q complicarse lol
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.AddRoundKey
-- Last modified : Fri May 08 16:43:39 2009
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;

entity AddRoundKey is
  port (
    Clk    : in     std_logic;
    Enable : in     std_logic;
    Finish : out    std_logic;
    KeyIn  : in     std_logic_vector(127 downto 0);
    Rst    : in     std_logic;
    TxtIn  : in     std_logic_vector(127 downto 0);
    TxtOut : out    std_logic_vector(127 downto 0));
end entity AddRoundKey;

--------------------------------------------------------------------------------
-- Object        : Architecture design.AddRoundKey.rtl
-- Last modified : Fri May 08 16:43:39 2009
--------------------------------------------------------------------------------


architecture rtl of AddRoundKey is
begin

ApplyKey : process (Clk)
begin 
	if(rising_edge(Clk)) then
		if(Rst = '1') then 
			TxtOut <= (others => '0');
			Finish <= '0';
		else 
	
			if(Enable = '1') then 
				TxtOut <= KeyIn xor TxtIn;
				Finish <= '1';
				
			else Finish <= '0';
			
			end if;
		end if;
	
	end if;
	
end process;



end architecture rtl ; -- of AddRoundKey

