--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.2 Revision 6 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : calypso1
-- User name     : RickWare
-- Time stamp    : Tue May 12 16:56:12 2009
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.CyperKey
-- Last modified : Tue May 12 16:47:03 2009.
--------------------------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;

entity CyperKey is
  port(
    KeyOut : out    std_logic_vector(127 downto 0));

end entity CyperKey ;

--------------------------------------------------------------------------------
-- Object        : Architecture design.CyperKey.rtl
-- Last modified : Tue May 12 16:47:03 2009.
--------------------------------------------------------------------------------

architecture rtl of CyperKey is

begin

end architecture rtl ; -- of CyperKey

