--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.4 Revision 4 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : v2-Lap
-- User name     : ricks
-- Time stamp    : Mon Apr 07 09:53:12 2025
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.CyperKey
-- Last modified : Tue May 12 15:47:03 2009
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;

entity CyperKey is
  port (
    KeyOut : out    std_logic_vector(127 downto 0));
end entity CyperKey;

--------------------------------------------------------------------------------
-- Object        : Architecture design.CyperKey.rtl
-- Last modified : Tue May 12 15:47:03 2009
--------------------------------------------------------------------------------


architecture rtl of CyperKey is

begin

end architecture rtl ; -- of CyperKey

