--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.2 Revision 6 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : calypso1
-- User name     : RickWare
-- Time stamp    : Tue May 12 16:56:12 2009
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.KeySchedule
-- Last modified : Tue May 12 12:23:51 2009.
--------------------------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;

entity KeySchedule is
  port(
    Clk    : in     std_logic;
    Enable : in     std_logic;
    Finish : out    std_logic;
    KeyIn  : in     std_logic_vector(127 downto 0);
    KeyOut : out    std_logic_vector(127 downto 0);
    Rst    : in     std_logic;
    Sel    : in     std_logic_vector(3 downto 0));

end entity KeySchedule ;

--------------------------------------------------------------------------------
-- Object        : Architecture design.KeySchedule.rtl
-- Last modified : Tue May 12 12:23:51 2009.
--------------------------------------------------------------------------------

architecture rtl of KeySchedule is

begin

end architecture rtl ; -- of KeySchedule

