--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 7.2 Revision 6 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : calypso1
-- User name     : RickWare
-- Time stamp    : Tue May 12 16:56:12 2009
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.ShiftRows
-- Last modified : Fri May 08 17:43:39 2009.
--------------------------------------------------------------------------------


library ieee;
use ieee.std_logic_1164.all;

entity ShiftRows is
  port(
    Clk    : in     std_logic;
    Enable : in     std_logic;
    Finish : out    std_logic;
    Rst    : in     std_logic;
    TxtIn  : in     std_logic_vector(127 downto 0);
    TxtOut : out    std_logic_vector(127 downto 0));

end entity ShiftRows ;

--------------------------------------------------------------------------------
-- Object        : Architecture design.ShiftRows.rtl
-- Last modified : Fri May 08 17:43:39 2009.
--------------------------------------------------------------------------------

architecture rtl of ShiftRows is

begin

end architecture rtl ; -- of ShiftRows

