--------------------------------------------------------------------------------
--
-- This VHDL file was generated by EASE/HDL 8.4 Revision 4 from HDL Works B.V.
--
-- Ease library  : design
-- HDL library   : design
-- Host name     : Laptop-Fer
-- User name     : ferna
-- Time stamp    : Mon Apr 07 09:58:08 2025
--
-- Designed by   : 
-- Company       : 
-- Project info  : 
--
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- Object        : Entity design.StateMach
-- Last modified : Tue May 12 11:55:40 2009
--------------------------------------------------------------------------------



library ieee;
use ieee.std_logic_1164.all;

entity StateMach is
  port (
    AddRoundu0En    : out    std_logic;
    AddRoundu0Fin   : in     std_logic;
    AddRoundu4En    : out    std_logic;
    AddRoundu4Fin   : in     std_logic;
    AddRoundu7En    : out    std_logic;
    AddRoundu7Fin   : in     std_logic;
    Clk             : in     std_logic;
    KeyEn           : out    std_logic;
    KeyFin          : in     std_logic;
    KeySel          : out    std_logic_vector(3 downto 0);
    MixColumnsu3En  : out    std_logic;
    MixColumnsu3Fin : in     std_logic;
    MuxSel          : out    std_logic;
    Rst             : in     std_logic;
    ShiftRowsu2En   : out    std_logic;
    ShiftRowsu2Fin  : in     std_logic;
    ShiftRowsu6En   : out    std_logic;
    ShiftRowsu6Fin  : in     std_logic;
    SubBytesu1En    : out    std_logic;
    SubBytesu1Fin   : in     std_logic;
    SubBytesu5En    : out    std_logic;
    SubBytesu5Fin   : in     std_logic);
end entity StateMach;

--------------------------------------------------------------------------------
-- Object        : Architecture design.StateMach.rtl
-- Last modified : Tue May 12 11:55:40 2009
--------------------------------------------------------------------------------


architecture rtl of StateMach is

begin

end architecture rtl ; -- of StateMach

